version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/ruby:2.6.10-node
        environment:
          BUNDLE_PATH: ~/vendor/bundle
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - run: cd spec/dummy; RAILS_ENV=test bundle exec rake db:setup

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format documentation \
                            --order rand \
                            $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      # Lint
      - run: yarn lint
      - run: yarn build
